package com.joklek.fakec.parsing.types;

public enum OperationType {
    MULT, DIV, ADD, SUB, MOD, NOT,
    LESS, LESS_EQUAL, GREATER, GREATER_EQUAL, EQUAL, EQUAL_EQUAL, NOT_EQUAL,
    PLUS_EQUAL, MINUS_EQUAL, MUL_EQUAL, DIV_EQUAL, MOD_EQUAL,
    INC_PRE, INC_POST, DEC_PRE, DEC_POST
}
